//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicFilter.SqlServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DynamicFilter.SqlServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  AND TBL.TABLE_NAME = @tableName.
        /// </summary>
        internal static string TABLE_METADATA_FILTER {
            get {
                return ResourceManager.GetString("TABLE_METADATA_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TBL.TABLE_NAME,
        ///       COL.COLUMN_NAME,
        ///       COL.DATA_TYPE,
        ///       COL.IS_NULLABLE,
        ///       PK = CASE
        ///              WHEN CPK.CONSTRAINT_NAME IS NULL THEN 0
        ///              ELSE 1
        ///            END,
        ///       FK = CASE
        ///              WHEN CFK.CONSTRAINT_NAME IS NULL THEN 0
        ///              ELSE 1
        ///            END
        ///FROM   INFORMATION_SCHEMA.TABLES TBL
        ///       INNER JOIN INFORMATION_SCHEMA.COLUMNS COL
        ///               ON COL.TABLE_NAME = TBL.TABLE_NAME
        ///                  AND COL.TABLE_SCHEMA = TBL.TABLE_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TABLE_METADATA_SQL2019_QUERY {
            get {
                return ResourceManager.GetString("TABLE_METADATA_SQL2019_QUERY", resourceCulture);
            }
        }
    }
}
